language: node_js
notifications:
  email: false
node_js:
  - '6.0.0'
before_install:
  - travis_retry nvm install 6.0.0
  - travis_retry wget https://www.dropbox.com/s/heja4ryn45bd5wt/test.tar.gz?dl=0 -O test.tar.gz && tar xfvz test.tar.gz
env:
  global:
    - MERGE_TOKEN=734cc2741e72f0c32e70f8e35bb85de538f90145
script:
  - npm test
